#!/bin/bash

conda activate kg_env_new

DATASET='simpsons'
RULE='full_data'

EMBEDDING_DIM=3
RGCN_EPOCHS=500
RGCN_LR=.001

TRACE_LENGTH=2

#./RGCN.py $DATASET $RULE $RGCN_EPOCHS $EMBEDDING_DIM $RGCN_LR

#./explaiNE.py $DATASET $RULE $TRACE_LENGTH $EMBEDDING_DIM

#MODEL='explaine'

#./eval.py $DATASET $RULE $MODEL $TRACE_LENGTH

GNN_NUM_EPOCHS=500
GNN_LR=.001

./GnnExplainer.py $DATASET $RULE $GNN_NUM_EPOCHS $EMBEDDING_DIM $GNN_LR

# MODEL='gnn_explainer'

# ./eval.py $DATASET $RULE $MODEL $TRACE_LENGTH