#!/bin/bash

#conda activate kg_env_new

DATASET='paul'
RULE='spouse'

RGCN_EPOCHS=20
EMBEDDING_DIM=10
RGCN_LR=.001

./RGCN.py $DATASET $RULE $RGCN_EPOCHS $EMBEDDING_DIM $RGCN_LR

TRACE_LENGTH=2

./explaiNE.py $DATASET $RULE $TRACE_LENGTH $EMBEDDING_DIM

#GNN_NUM_EPOCHS=1
#GNN_LR=.001

#./GnnExplainer.py $DATASET $RULE $GNN_NUM_EPOCHS $EMBEDDING_DIM $GNN_LRS